# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCOrUwszo9Vv5LkxxQkH0umEw-6vgPEs
"""

pip install yfinance

import yfinance as yf

msft = yf.Ticker("MSFT")

# get all stock info (slow)
msft.info

msft.history_metadata

import yfinance as yf

alibaba = yf.Ticker("BABA")
history = alibaba.history(period="max")
print(history)

import yfinance as yf
import matplotlib.pyplot as plt

alibaba = yf.Ticker("BABA")
history = alibaba.history(period="max")

plt.plot(history.index, history['Close'])
plt.title('Alibaba Stock Price History')
plt.xlabel('Date')
plt.ylabel('Price')
plt.show()